### ISSUE TITLE
Add behat?

### ISSUE THREAD

**Issue by shouze** [phar-io/phar.io#111]

**Comment by theseer** [comment]
?

**Comment by shouze** [comment]
@theseer I mean can I contribute to add it?

**Comment by theseer** [comment]
To do what exactly?

**Comment by shouze** [comment]
To be able to install it through phive

**Comment by theseer** [comment]
`phive install --force-accept-unsigned behat/behat`

If you want to avoid the `--force-acecpt-unsigned`-switch, make them sign their releases.

**Comment by shouze** [comment]
@theseer thank you!
I just wonder: when we want to use extensions (behat, phpstan, ...) how can we proceed so far?
For example this one: https://github.com/PedroTroller/PhpCSFixer-Custom-Fixers

If I keep it as a composer dev dependency, it will require php-cs-fixer but I want to avoid installing it as a dev dependency by using phive... so... I feel a bit trapped, any recommandation on that topic?

**Comment by theseer** [comment]
Nothing much we can do from `phive`'s perspective here as the way they designed extensions to be loaded/added as well as distributed is conceptually based on a mixed source installation.

If you want to have a `phar` matching your setup the only thing I can offer is to build your own based on a full source tree with all extensions added. This can easily be automated and quite some people actually do that, placing the resulting phar into a private repository.

Alternatively, the projects supporting extensions needs to provide a clean way to load them, e.g. like PHPUnit, from an extension-phar. An example for a PHPUnit extension can be found [here](https://github.com/sebastianbergmann/phpunit-example-extension).

In theory `phive` could install such an extension. In theory, because we didn't implement that yet due to logical constraints that need solving first. More here: https://github.com/phar-io/phive/issues/88

**Comment by shouze** [comment]
Very clear, the only way I've found is to use replace in composer.json and still install extensions apart as dev dependencies for example. Not ideal but this way dev dependencies remains less polluted by dev tooling.
