### ISSUE TITLE
Reliability of phar.io website to install in CI

### ISSUE THREAD

**Issue by echoix** [phar-io/phar.io#148]
In the last couple months, the step of installing phive in a Docker image for all the Megalinter images/flavors has been really flaky, for no apparent reason. About 2-3 times a week at least, it causes failed builds. Apart from another website for our docs side, it is the number one unexplained transient failure reason in our workflows.

At first we thought that it was us using old installation instructions, and thus querying dead gpg key servers, or the phar.io server isn't stable. Everytime it failed, I opened phar.io and the site loads normally. But now I caught something that I didn't catch my eye before because it was higher in the logs:
https://github.com/oxsecurity/megalinter/actions/runs/7333098014/job/19968135349#step:8:301

This lets me think that my second hypothesis might be right. What could be happening ?
We are already sending a token (I'm not totally comfortable now that we try to limit the permissions of GitHub tokens in all workflows), and we fixed the keyservers, adding the more reliable hkps://keys.openpgp.org, and placed it first.

What's frustrating is that immediately relaunching the failed job does not fail, so it doesn't sound to me like if it were to be a rate limiting issue from our side, as a second run in such short time should fail for the same reason. 

You can go through the logs for our actions, in various workflows, but it's hard to filter out for a specific job of a matrix, and only previous failed run (since we retry failed jobs manually if needed).

Here it looks like the phar.io website does API requests to github on each call, https://github.com/phar-io/phar.io/blob/94c6e1c2430c86bfaa4dfaee100e4ae7f23716a7/php/release.php
But, https://github.com/phar-io/phar.io/issues/113#issuecomment-992533669 seems to indicate that a nginx solution was applied. Is it still active?

**Comment by theseer** [comment]
Thank you for reporting an issue.  Unfortunately, I'm not convinced that our website is causing reliability issue for CI runs. Apart from the original download when using our release-redirector and the occasional update of the `repositories.xml`, Phive has been designed to NOT require our site to be operational.

The first, rather naive approach to having a generic redirect to the latest release indeed used an API call to github. As releases aren't that frequent these days (unfortunately), this didn't make any sense anymore and got finally replaced by an nginx side static redirect that we'll update upon new releases. We just didn't remove the code yet.

But that's not actually your problem: The referenced line in the logs says `wget: bad address "phar.io"`. So the worker node has a DNS issue. It doesn't even get to our server, let alone following the redirect.

I'm not sure what the issue here might be, as to why our DNS should have reoccurring issues. We can't do much to improve github's DNS resolving - which seems to be a commong problem when googling for the above error message.

On the other hand,. I do not understand why you have to re-build and re-download your environment for every CI run? Maybe that's required as part of your pipeline - after all,  I didn't check any details and what you're doing here - but frequently a lot of redundant work is done.

Couldn't you create your own "static" Container Image once and then use it for all other runs until further notice? ;-) 
You could potentially also use the Container image of phive. We have a minified container image on docker hub (https://hub.docker.com/r/phario/phive).
