### ISSUE TITLE
PHAR supported by project "Baseline for PHP CS Fixer"

### ISSUE THREAD

**Issue by Aeliot-Tm** [phar-io/phar.io#157]
Hi @theseer 

I added support of PHAR to may repo. And signed it with GPG key. 
What my next steps to make it accessible via Phive?

Link to release with PHAR: https://github.com/Aeliot-Tm/php-cs-fixer-baseline/releases/tag/v1.2.0

**Comment by Aeliot-Tm** [comment]
![image](https://github.com/user-attachments/assets/c0ab476f-7729-48a7-b670-996a45b9ac7e)

**Comment by Aeliot-Tm** [comment]
As I can see, the problem is in the difference of the vendor name of package and the username of repository where the package is hosted. How could I help for PHIVE installer to use proper repository?
![image](https://github.com/user-attachments/assets/4925a5c0-dbc6-4027-a7e0-b535512561a2)

**Comment by theseer** [comment]
Why not use `aeliot-tm/php-cs-fixer-baseline`?

**Comment by theseer** [comment]
For the record: Phive doesn't really care about composer / packagist naming as it's independent from it, it's just a convention adopted as people are familiar with it and of course because the pattern makes sense.

As can be seen in the URLs accessed in your example, when the passed argument is containing a single `/`, phive is considering it a `namespace/project-name`, trying github as well as gitlab using their respective formats. 

A 3rd option is to register an alias with us, so people can use "php-cs-fixer-baseline" for instance, and phive would know where to get the files as they are pre-resolved: https://phar.io/distribute-your-own.html

**Comment by Aeliot-Tm** [comment]
@theseer Thank you so much!

I'll  provide alias for the project. 

Did not see this instruction about distribution before. May be it would be nice to have some menu on the site for better navigation 😃

**Comment by theseer** [comment]
![image](https://github.com/user-attachments/assets/3d245d81-fc1f-486d-b9c1-45a28b912a6c)


"Distribute your own" is on the main navigation :)

**Comment by Aeliot-Tm** [comment]
@theseer I created PR. Could you accept it?
https://github.com/phar-io/phar.io/pull/158
