### ISSUE TITLE
No matching release found for sensiolabs/security-checker

### ISSUE THREAD

**Issue by Ig0r-M-magic42** [phar-io/phar.io#84]
Hi, i am new to phive so still a lot of unexplored land for me. Wanted to see if it's something i can contribute for https://github.com/sensiolabs/security-checker repo to allow phive to install it. Below you can see the command output and also link to where releases should be listed.
```
root@project:/vagrant# phive install sensiolabs/security-checker
Phive 0.14.4 - Copyright (C) 2015-2020 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/rate_limit
[ERROR]    No matching release found! 
```
https://api.github.com/repos/sensiolabs/security-checker/releases

## Goal
- [ ] Allow for repo https://github.com/sensiolabs/security-checker to be installed via phive

**Comment by theseer** [comment]
Thank you for considering to contribute!

As you probably already guessed, `phive` requires a - preferably gpg signed - phar archive to install.

While https://github.com/sensiolabs/security-checker apparently uses and publishes tags to mark releases, they do not really seem to make much use of the releases support on github otherwise. So currently, that doesn't work as a source for `phive` to install from. 

There seems to be a phar version of it, but the arbitrary download link provided in the [README.md](https://github.com/sensiolabs/security-checker/blob/master/README.md#L50) is rather useless when it comes to automation.

To make things work with `phive`, you may want to read https://phar.io/distribute-your-own.html and come back here if there are remaining questions :)

**Comment by Ig0r-M-magic42** [comment]
Thanks for letting me know @theseer , it seem from the distribute your own docs that owner or maintainer of the repo can only do this.

Also i've opened this https://github.com/phar-io/phar.io/pull/85, would you mind taking a look.

**Comment by theseer** [comment]
> Thanks for letting me know @theseer , it seem from the distribute your own docs that owner or maintainer of the repo can only do this.

Yes. At least the actual release and signing has to be triggered by an "authorized" person. But of course - at least in theory - anybody could create the required scripting to automate that.

> 
> Also i've opened this #85, would you mind taking a look.

Nice catch. Your guess for the correct link was wrong though, but I updated it. Thanks!

I'll close this, as from phive's perspective, I believe there is nothing we can do.
